selmag:
  services:
    catalogue:
      url: http://localhost:8081
      username: catalogue_service_user
      password: password

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/manager
    username: manager
    password: manager
  flyway:
    schemas:
      - user_management
    locations: db/migration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect